# Generated by Django 4.0.3 on 2022-04-10 16:16

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flavour', models.CharField(blank=True, max_length=45, null=True)),
                ('amount_sold', models.IntegerField(default=0)),
                ('out_of_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
