# Generated by Django 4.0.3 on 2022-04-12 12:36

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_protein_protein_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('out_of_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='protein',
            name='amount_sold',
        ),
    ]
