# Generated by Django 4.0.3 on 2022-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_clothing_remove_protein_amount_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('X', 'X'), ('XL', 'XL')], default='S', max_length=2),
        ),
    ]
