# Generated by Django 4.0.3 on 2022-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_clothing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='type',
            field=models.TextField(default='Clothing'),
        ),
        migrations.AddField(
            model_name='protein',
            name='type',
            field=models.TextField(default='Protein'),
        ),
    ]
