# Generated by Django 4.0.3 on 2022-04-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='product_id',
            new_name='product',
        ),
    ]
