# Generated by Django 4.0.3 on 2022-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_buyer_id_sales_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
