# Generated by Django 4.0.3 on 2022-04-09 21:32

import FitnessStore.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5), FitnessStore.common.validators.validate_only_letters])),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('test_param', models.TextField(max_length=25)),
            ],
        ),
    ]
