# Generated by Django 4.0.3 on 2022-04-09 22:14

import FitnessStore.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2), FitnessStore.common.validators.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2), FitnessStore.common.validators.validate_only_letters]),
            preserve_default=False,
        ),
    ]
