# Generated by Django 4.0.3 on 2022-04-09 23:40

import FitnessStore.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessstoreuser',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5), FitnessStore.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), FitnessStore.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), FitnessStore.common.validators.validate_only_letters]),
        ),
    ]
